blogApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
]

blogs/urls.py
from django.urls import path
from . import views
# To view static files and images
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

app_name = 'blogs'
urlpatterns = [
       path('', views.index, name = 'Home'),
       path('about/', views.about, name='About'),
       path('contact/', views.contact, name='Contact'),
       path('signup/', views.signup_view, name = 'Signup'),
       path('login/', views.login_view, name='Login'),
       path('logout/', views.logout_view, name='Logout'),
       path('change_password/', views.change_password, name='ChangePassword'),
       path('profile/', views.profile, name = 'Profile'),
       path('addBlogs/', views.addBlogs, name='AddBlogs'),
       path('updateBlogs/<int:id>', views.updateBlogs, name='UpdateBlogs'),
       path('deleteBlogs/<int:id>', views.deleteBlogs, name='DeleteBlogs'),
       path('viewBlog/<int:id>', views.viewBlogs, name = 'ViewBlog'),
       path('blogs/', views.allBlogs, name='AllBlogs'),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
# Create your models here.
class BlogPost(models.Model):
    title = models.CharField(max_length=100, verbose_name = 'Blog Title')
    description = models.TextField(verbose_name='Blog Description')
    author = models.ForeignKey(User, on_delete=models.CASCADE, db_column='user', default=1,null=True, blank=True)
    pub_date = models.DateTimeField(verbose_name='Published Date',default=timezone.now)
    image = models.ImageField(verbose_name='Upload Picture', blank=True, upload_to='media/')
    featured = models.BooleanField(verbose_name='Is Featured', blank=False, default=False)

    def __str__(self):
        return self.title

    def short_des(self):
        return self.description[:100]

    def isFeatured(self):
        self.featured = True

    class Meta:
        ordering = ['title']

blogs/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.utils.translation import gettext, gettext_lazy as _
from . import models


class CreateUserForm(UserCreationForm):
    password1 = forms.CharField(label='Password',
                widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ['first_name','last_name','email','username']
        widgets = {
        'first_name': forms.TextInput(attrs={'class':'form-control'}),
        'last_name': forms.TextInput(attrs={'class':'form-control'}),
        'email': forms.EmailInput(attrs={'class':'form-control'}),
        'username': forms.TextInput(attrs={'class':'form-control'})
        }

class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus':True, 'class':'form-control'}))
    password = forms.CharField(label=_('Password'), strip=False,
                widget=forms.PasswordInput(attrs={'autocomplete':'current_password', 'class':'form-control'}))

class BlogsForm(forms.ModelForm):
    class Meta:
        model=models.BlogPost
        fields = ['title', 'description', 'image']
        labels = {
            'title': 'Blogs Title',
            'description': 'Blog Description',
            'image' : 'Upload a Picture',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Enter Blog title here'}),
            'description': forms.Textarea(attrs={'placeholder':'Enter Blog description'}),
        }

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import PasswordChangeForm
from .forms import CreateUserForm, LoginForm as AuthenticationForm, BlogsForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.models import Group
import random
from .models import BlogPost
from django.contrib.auth.models import User

# Homepage View


def index(request):
    if not request.user.is_authenticated:
        check_session(request)
    featured_post = BlogPost.objects.filter(featured=True)
    index = random.shuffle(featured_post)
    blogs = BlogPost.objects.all()
    # print(request.user)
    context = {
        'blogs': blogs,
        'featured': featured_post,
    }
    return render(request, 'blogs/index.html', context)

# View for Signup


def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                user = form.save()
                group = Group.objects.get(name='Author')
                user.groups.add(group)
                messages.success(request, 'Account Created successfully')
                return redirect('/login/')
        else:
            form = CreateUserForm()
        return render(request, 'blogs/signup.html', context={'form': form})
    else:
        return redirect('/profile/')

# Check Session authentication
def check_session(request):
    if 'username' in request.session and 'password' in request.session:
        user = authenticate(request,
            password=request.session.get('password'),
            username=request.session.get('username'))
        # print(request.session['username'],request.session['password'])
        if user is not None:
            login(request, user)
            messages.success(request,'You are logged in')
            # if 'next' in request.POST:
            #     return redirect(request.POST.get('next'))
            # return redirect('/')

# View for Login

def login_view(request):
    if not request.user.is_authenticated:
        check_session(request)
        if request.method == 'POST':
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                print(username, password)
                user = authenticate(username=username, password=password)
                if user is not None:
                    if True in request.POST.getlist('remember'):
                        request.session['username'] = username
                        request.session['password'] = password

                    login(request, user)
                    messages.success(request, "you are logged in successfully")
                    if 'next' in request.POST:
                        return redirect(request.POST.get('next'))
                    return redirect('/profile/')
        else:
            form = AuthenticationForm()  #Request is GET
        return render(request, 'blogs/login.html', {'form': form})
    else:
        return redirect('/profile/')

# View for Logout


@login_required(login_url='/login/')
def logout_view(request):
    logout(request)
    request.session.flush()
    messages.info(request, 'You are Logged out!')
    return redirect('/')

# View for profile Dashboard


@login_required(login_url='/login/')
def profile(request):
    if request.user.is_authenticated:
        blogs = BlogPost.objects.all()
        return render(request, 'blogs/profile.html', context={'posts': blogs})
    else:
        return redirect('/login/')

# view for About page


def about(request):
    return render(request, 'blogs/about.html')

# VIew for Contact Page


def contact(request):
    return render(request, 'blogs/contact.html')

# View for Change Password


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password has been changed')
            return redirect('/profile/')
    else:
        form = PasswordChangeForm(user=request.user)

    return render(request, 'blogs/changePassword.html', {'form': form})

# Add Blogs View


@login_required(login_url='/login/')
def addBlogs(request):
    if request.method == 'POST':
        form = BlogsForm(request.POST, request.FILES)
        if form.is_valid():
            blog = form.save()
            blog.author = request.user
            messages.success(request, 'Blogs has been added successfully')
            form = BlogsForm()
    else:
        form = BlogsForm()
    return render(request, 'blogs/addBlogs.html', {'form': form})

# Edit Post View


@login_required(login_url='/login/')
def updateBlogs(request, id):
    if request.method == 'POST':
        blog = BlogPost.objects.get(pk=id)
        form = BlogsForm(request.POST, request.FILES, instance=blog)
        if form.is_valid():
            blog = form.save()
            if request.POST['id_featured']:
                blog.featured = True
                blog.save()
            messages.success(request, 'Blog updated successfully')
            return redirect('/profile/')
    else:
        blog = BlogPost.objects.get(pk=id)
        form = BlogsForm(instance=blog)
    return render(request, 'blogs/updateBlogs.html', context={'form': form})


# Delete Post View
@login_required(login_url='/login/')
@permission_required('blogs.delete_blogPost')
def deleteBlogs(request, id):
    if request.method == 'POST':
        blog = BlogPost.objects.get(pk=id)
        blog.delete()
        messages.success(request, "Blog deleted successfully")
        return redirect('/profile/')
    return redirect('/profile/')


def viewBlogs(request, id):
    blog = BlogPost.objects.get(pk=id)
    user = User.objects.get(pk=blog.author.pk)
    return render(request, 'blogs/blog.html', context={
        'blog': blog,
        'author': user
    })

def allBlogs(request):
    blogs = BlogPost.objects.all()
    return render(request,'blogs/bloglist.html',{'blogs':blogs})

blogs/templates/blogs/about.html
{% extends "base.html" %}
{% load cache %}
{% block title %}
    About Us
{% endblock %}

{% block content %}
    <div class="col-sm-10">
        {% cache 300 about %}
        <h3 class='display-3 font-weight-bold'>About Us</h3>
        <p class='text-justify'>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            <br><br>tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            orem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                <br><br>tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip e
            {% endcache about %}
            <h2>Director</h2>
            <h3>Govinda Neupane</h3>
    </div>
{% endblock %}

blogs/templates/blogs/addBlogs.html
{% extends "base.html" %}
{% load static %}

{% block Styles %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}
{% block title %}

{% endblock %}
{% block content %}
    <div class="col-sm-10">
        <h3 class='text-secondary'><a class='text-decoration-none' href="{% url 'blogs:Profile' %}">Dashboard</a>/
            <a class='text-decoration-none' href="#">Add Blogs</a> </h3>
        <form action="" method="post" enctype='multipart/form-data'>
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" name="submit" value="Add" class='btn btn-register'>
            <input type="reset" name="reset" value="Cancel" class='btn btn-reset'>
        </form>
    </div>
{% endblock %}

blogs/templates/blogs/blog.html
{% extends "base.html" %}
{% block Styles %}
    <style media="screen">
        .blog{
            background-color: rgb(178,168,168);
        }
        .text-right{
            margin-left: 50%;
        }

        .image{
            max-width: 100%;
        }
        .blog-img{
            max-width: 100%;
        }
    </style>
{% endblock %}
{% block title %}
    {{blog.title}}
{% endblock %}

{% block content %}
        {% if request.user.is_authenticated %}
            <h2><a href="{% url 'blogs:Profile' %}">Dashboard</a>/<a href="#">View Blogs</a> </h2>
        {% endif %}
        <div class="col-sm-10">
        <div class="col-sm-6 blog">
            <h2 class='display-4'>{{blog.title}}</h2>
            <p class="text-justify">{{blog.description}}</p>
            <p><span class="text-muted text-left font-weight-bold">Author: {{user.get_full_name}}</span>
                <span class="text-right text-secondary">{{blog.pub_date}}</span></p>
        </div>
        <div class="col-sm-6 image">
            <img class="blog-img" src="/media/{{blog.image}}" alt="{{blog.image}}">
        </div>
    </div>
{% endblock %}

blogs/templates/blogs/bloglist.html
{% extends "base.html" %}
{% block Styles %}
<style media="screen">
    .blog {
        background-color: rgb(178, 168, 168);
    }

    .text-right {
        margin-left: 60%;
    }

    .image {
        max-width: 100%;
    }

    .blog-img {
        width: 100%;
    }
</style>
{% endblock %}
{% block title %}
{{blog.title}}
{% endblock %}

{% block content %}
<div class="col-sm blog">
    <h1 class='display-1 text-center'>Blogs</h1>
    <br>
    {% for blog in blogs  %}
    <table>
        <tr>
            <td scope="col" style="width:100%">
                <h2 class='display-4'>{{blog.title}}</h2>
            </td>
        </tr>
        <tr>
            <td scope="col" style="width:50%">
                <p class="text-justify">{{blog.description}}</p>
                <p><span class="text-muted text-left font-weight-bold">Author: {{blog.author.get_full_name}}
                    </span><span class="text-right text-secondary"><i>Published:{{blog.pub_date}}</i></span></p>
            </td>
            <td style="width:50%">

                <img class="blog-img" src="/media/{{blog.image}}" alt="{{blog.image}}">
            </td>
        </tr>
    </table>
    {% endfor %}

</div>
{% endblock %}

blogs/templates/blogs/changePassword.html
{% extends "base.html" %}
{% load static %}
{% block Styles %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}
{% block title %}
Change Password
{% endblock %}

{% block content %}
<form action="" method="post" id='inputForm'>
    {% csrf_token %}
    <fieldset>
        <legend> Login Form</legend>
        {% if form.non_field_errors %}
               {% for errors in form.non_field_errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Error</strong> {{errors}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
           {% endif %}
    {% for fm_data in form  %}
        <div class="form-group">
            {{fm_data.label_tag}}<br>
            {{fm_data}}  {{fm_data.errors|striptags}}<br>
        </div>
    {% endfor %}
    <br>
        <div class="button-group">
            <input type="submit" name="SignUp" value="Change Password" class="btn btn-register px-5">
            <input type="reset" name="Reset" value="Cancel" class='btn btn-reset px-5'>
        </div><br>

</fieldset>
</form>
{% endblock %}

blogs/templates/blogs/contact.html
{% extends "base.html" %}
{% load static %}
{% load cache %}
{% block Styles %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}
{% block title %}
    Contact Us
{% endblock %}
{% block content %}
    <div class="col-sm-12">
        {% cache 300 contact %}
        <h1 class='text-dark text-center'>Contact Us</h1>
        <form id='inputForm'>
          <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" placeholder="Enter Your Name">
        </div><br>
          <div class="form-group">
            <label for="phone">Another label</label>
            <input type="text" class="form-control" id="phone" placeholder="Phone Number">
        </div><br>
        <div class="form-group">
            <label for="message">Message</label><br>
            <textarea name="name" rows="10" placeholder='Enter you Message here'></textarea>
        </div>
        <div class="button-group">
                <input type="submit" name="submit" value="Submit" class='btn btn-register'>
                <input type="reset" name="reset" value="Cancel" class='btn btn-reset'>
        </div>
    </form><br>
    {% endcache contact %}
    </div>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "base.html" %}
{% block title %}
    Homepage
{% endblock %}
<div class='col-md-4'>
    {% block content %}
    <main class='container'>
        {% for post in featured  %}
        <div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
            <div class="col-md-6 px-0">
                <h1 class="display-4 fst-italic">{{post.title}}</h1>
                <p class="lead my-3">{{post.short_des}}...</p>
                <p class="lead mb-0"><a href="{% url 'blogs:ViewBlog' post.id %}" class="text-white fw-bold">Continue reading...</a></p>
            </div>
        </div>
        {% endfor %}
        <div class="row mb-2">
        {% for post in blogs  %}

            <div class="col-md-6">
                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                    {% if post.image %}
                    <div class="col-sm-6 p-4 d-flex flex-column position-static" width='400px'>
                        <strong class="d-inline-block mb-2 text-primary">World</strong>
                        <h3 class="mb-0">{{post.title}}</h3>
                        <div class="mb-1 text-muted">{{post.pub_date}}</div>
                        <p class="card-text mb-auto">{{post.short_des}}...</p>
                        <a href="{% url 'blogs:ViewBlog' post.id %}" class="stretched-link">Continue reading</a>
                    </div>

                    <div class="col-sm-6 d-none d-lg-block my-auto">
                        <img src="media/{{post.image}}" alt="{{post.image}}" class="img-thumbnail">
                    </div>
                    {% else %}
                    <div class="col-sm-12 p-4 d-flex flex-column position-static" >
                        <strong class="d-inline-block mb-2 text-primary">World</strong>
                        <h3 class="mb-0">{{post.title}}</h3>
                        <div class="mb-1 text-muted">{{post.pub_date}}</div>
                        <p class="card-text mb-auto">{{post.short_des}}</p>
                        <a href="#" class="stretched-link">Continue reading</a>
                    </div>
                    {% endif %}
                </div>
            </div>

        {% endfor %}
        </div>
    </main>
    {% endblock %}
</div>

blogs/templates/blogs/login.html
{% extends "base.html" %}
{% load static %}
{% block Styles %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}
{% block title %}
    User Login
{% endblock %}

{% block content %}
<form action="" method="post" id='inputForm'>
    {% csrf_token %}
    <fieldset>
        <legend> Login Form</legend>
        {% if form.non_field_errors %}
               {% for errors in form.non_field_errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Error</strong> {{errors}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
           {% endif %}
    {% for fm_data in form  %}
        <div class="form-group">
            {{fm_data.label_tag}}<br>
            {{fm_data}}  {{fm_data.errors|striptags}}<br>
        </div>
    {% endfor %}
    <!--<div class="form-check">
        <label for="remember" class="form-check-label">
            <input type="checkbox" class="form-check-input" name="remember" id="remember" value="True"> Remember Me </label>
    </div>-->
    {% if request.GET.nex %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
        <div class="button-group">
            <input type="submit" name="Login" value="Login" class="btn btn-register px-5">
            <input type="reset" name="Reset" value="Cancel" class='btn btn-reset px-5'>
        </div><br>

</fieldset>
</form>
{% endblock %}

blogs/templates/blogs/profile.html
{% extends "base.html" %}
{% block Styles %}
    <style media="screen">
        table, tr, td, th{
            border: 2px solid green;
            border-bottom: 4px double;
            border-collapse: collapse;
        }
    </style>
{% endblock %}
{% block title %}
    {{request.user.get_full_name}}
{% endblock %}
{% block side %}
        <div class="col-sm-2 my-5 text-center">
                <h4 class='text-success my-5'>Profile Name</h4>
                <h5>{{request.user.get_full_name}}</h5>
                {% for groups in request.user.groups.all  %}
                    <p>{{groups}}</p>
                {% endfor %}
        </div>
{% endblock side %}
{% block content %}
    <div class="col-sm-10">
        <h3 class='text-primary my-5 '>Dashboard Page</h3>
        <a href="{% url 'blogs:AddBlogs' %}" class='btn btn-success font-weight-bold'>Add Blogs</a>
        <h4 class='text-center alert alert-info mt-3'>Show Post Information</h4>
            {% if posts %}
                <table>
                    <thead>
                        <tr class="text-center">
                            <th scope="col" style="width:15%">TITLE</th>
                            <th scope="col" style="width:35%" class='text-justify'>DESCRIPTION</th>
                            <th scope="col" style="width:15%">PUBLISHED</th>
                            <th scope="col" style="width:20%">ACTION</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in posts  %}
                            <tr>
                                <td>{{post.title}}</td>
                                <td>{{post.description}}</td>
                                <td>{{post.pub_date}}</td>
                                <td class='text-center'>
                                    <a href="{% url 'blogs:ViewBlog' post.id %}" class='btn btn-primary btn-sm'>View</a>
                                    <a href="{% url 'blogs:UpdateBlogs' post.id %}" class='btn btn-warning btn-sm'>Edit</a>

                                    {% if perms.blogs.delete_Blogs %}
                                    <form action="{% url 'blogs:DeleteBlogs' post.id %}" method="post" class='d-inline'>{% csrf_token %}
                                        <input type="submit" class="btn btn-danger btn-sm" value="Delete">
                                    </form>{% endif %}
                                    </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <h4 class="text-center alert alert-warning">No Records Found</h4>
            {% endif %}
    </div>
{% endblock %}

blogs/templates/blogs/signup.html
{% extends "base.html" %}
{% load static %}
{% block Styles %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
{% endblock %}
{% block title %}
    User Registration
{% endblock %}

{% block content %}
<form action="" method="post" id='inputForm'>
    {% csrf_token %}
    <fieldset>
        <legend> Registration Form</legend>
        {% if form.non_field_errors %}
               {% for errors in form.non_field_errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Error</strong> {{errors}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
           {% endif %}
    {% for fm_data in form  %}
        <div class="form-group">
            {{fm_data.label_tag}}
            {{fm_data}}  {{fm_data.errors|striptags}}
        </div>
    {% endfor %}
    <br>
        <div class="button-group">
            <input type="submit" name="SignUp" value="Sign Up" class="btn btn-register px-7">
            <input type="reset" name="Reset" value="Cancel" class='btn btn-reset px-7'>
        </div><br>

</fieldset>
</form>
{% endblock %}

blogs/templates/blogs/updateBlogs.html
{% extends "base.html" %}
{% load static %}

{% block Styles %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">

{% endblock %}
{% block title %}

{% endblock %}
{% block content %}
    <div class="col-sm-10">
        <h3 class='text-secondary'><a class='text-decoration-none' href="{% url 'blogs:Profile' %}">Dashboard</a>/
            <a class='text-decoration-none' href="#">Update Blog Post</a></h3>
        <form action="{% url 'blogs:Profile' %}" method="post">
            {% csrf_token %}
            {{form.as_p}}
            {% ifequal request.user.id 1 %}
                <input type="checkbox" name="id_featured" value="featured">Mark as Featured <br><br>
            {% endifequal %}
            <input type="submit" name="submit" value="Update" class='btn btn-register'>
            <input type="reset" name="reset" value="Cancel" class='btn btn-reset'>
        </form>
    </div>
{% endblock %}